from nltk.corpus import treebank
from nltk.tree import Production
import re
import nltk
import random
import config
import glob
import time


# used to print progress
def nap():
    time.sleep(1)


# tree to string
def get_string(tree):
    str_tree = str(tree).replace('\n', '')
    return ' '.join(str_tree.split()) + '\n'


# to capture numbers with special token
def is_num(word):
    return re.search('[a-zA-Z*]', word) is None and re.search('[0-9]', word) is not None and word != '0'


# compares terminal in production with token in sentence
def is_valid(terminal, word):
    if terminal == str.lower(word):
        return True
    if terminal == '<NUM>' and is_num(word):
        return True
    return False


# generate training test split of treebank fileids
def get_training_and_test_split(config):
    files = treebank.fileids()
    random.shuffle(files)
    training = files[:int(0.9 * len(files))]
    test = files[int(0.9 * len(files)):]

    with open(config.train_set, 'w') as file:
        file.write(",".join(training))

    with open(config.test_set, 'w') as file:
        file.write(",".join(test))


# parse production rule
def parse_production(rule: Production):
    lhs = rule.lhs().symbol()
    rhs = rule.rhs()
    # check if rhs is terminal
    if rule.is_lexical():
        rhs = str.lower(rhs[0])
        # replace with <NUM> if its number
        if is_num(rhs):
            rhs = "<NUM>"
    else:
        rhs = " ".join([nt.symbol() for nt in rhs])
    return lhs, rhs


# gives base parse category
def base_category(t):
    if isinstance(t, nltk.tree.Tree):
        m = re.match("^(-[^-]+-|[^-=]+)", t.label())
        if m is not None:
            t.set_label(m.group(1))


# stitch files generated by each process
def stitch_files():
    print("Stitching files")
    gold_list = sorted(glob.glob(config.target_folder + "/gold*"))
    result_list = sorted(glob.glob(config.target_folder + "/result*"))

    if len(gold_list) != len(result_list):
        raise Exception("Results and Gold didn't match")

    gold = []
    result = []
    for i in range(len(gold_list)):
        with open(gold_list[i]) as f:
            gold.append(f.read().strip('\n'))
        with open(result_list[i]) as f:
            result.append(f.read().strip('\n'))

    with open(config.target_folder + '/gold.txt', 'w') as f:
        f.write("\n".join(gold))
    with open(config.target_folder + '/result.txt', 'w') as f:
        f.write("\n".join(result))
